[package]
name = "led_sender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "led_sender"
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.5.0"
pyo3 = "0.22.0"
socket2 = "0.5.3"