AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scambilight

  Sample SAM Template for scambilight

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      # AllowCredentials: true  Uncomment only if you choose a specific origin instead of the * wildcard.
  Function:
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        SCAMBIFOLDER: "scambilight"
        SCAMBIWEB: "scambilight.com"
        SCAMBIIMAGES: "images"
        SCAMBICONFIG: "config"
        OVERLAY_IMAGE: "overlay_image.jpg"
        RAW_IMAGE: "raw_image.jpg"
        CONFIG_FILE: "config.json"
        SAMPLE_CONFIG_FILE: "SAMPLE_CONFIG_FILE.json"
        EVENT_QUEUE_URL: !Ref SqsQueueEvents # Gets SQS Queue URL
        EVENTS_TABLE: !Ref MyEventTable
    Tracing: Active
  #Api:
  #  TracingEnabled: true
Resources:
  UploadSomething:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: scambi/
      Handler: upload.lambda_handler
      Runtime: python3.9
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Architectures:
      - x86_64
      Events:
        Uploader:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: POST
      Policies:
        - S3FullAccessPolicy:
            BucketName: scambilight # bucket name without arn
        - S3FullAccessPolicy:
            BucketName: scambilight.com # bucket name without arn
        - SQSPollerPolicy:
            QueueName:
              !GetAtt SqsQueueEvents.QueueName
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt SqsQueueEvents.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref MyEventTable
  
  SqsQueueEvents:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: user_events
      MessageRetentionPeriod: 120
      Tags:
        - Key: Name
          Value: user_events

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
  
  MyEventTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: event
        Type: String

Outputs:
  CreateOrdersAPI:
    Description: "API Gatseway endpoint url for creating orders"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"