// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hello {
    #[prost(string, tag="1")]
    pub device_id: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
